"use client";

import { createContext, useContext } from "react";

// Legacy helper signatures accept both values; the app supplies English only.
export type AppLanguage = "en" | "mr";

const translations: Record<string, string> = {
  "dashboard": "Dashboard",
  "items": "Items",
  "categories": "Categories",
  "units": "Units",
  "settings": "Settings",
  "add": "Add",
  "edit": "Edit",
  "delete": "Delete",
  "save": "Save",
  "cancel": "Cancel",
  "search": "Search",
  "voice_search": "Voice Search",
  "name": "Name",
  "price": "Price",
  "quantity": "Quantity",
  "category": "Category",
  "unit": "Unit",
  "buy_price": "Buy Price",
  "sell_price": "Sell Price",
  "margin": "Margin",
  "low_stock": "Low Stock Limit",
  "total_items": "Total Items",
  "low_stock_items": "Low Stock Items",
  "total_value": "Total Inventory Value",
  "avg_margin": "Average Margin",
  "language": "Language",
  "english": "English",
  "no_items": "No items found",
  "add_item": "Add Item",
  "edit_item": "Edit Item",
  "add_category": "Add Category",
  "edit_category": "Edit Category",
  "add_unit": "Add Unit",
  "edit_unit": "Edit Unit",
  "confirm_delete": "Are you sure?",
  "success": "Success",
  "error": "Error",
  "home": "Home",
  "stock": "Stock",
  "udhari": "Udhari",
  "new_sale": "New Sale",
  "logout": "Logout",
  "sale": "Sale",
  "dukan": "MediShop",
  "general": "General",
  "today_sales": "Today's sales",
  "today_profit": "Today's profit",
  "bills_today": "Bills today",
  "needs_attention": "Needs attention",
  "view_all": "View all",
  "todays_sales_activity": "Today's sales activity",
  "business_intelligence": "Business intelligence",
  "inventory_health": "Inventory health",
  "money_to_recover": "Money to recover",
  "expiry_alerts": "Expiry alerts",
  "view_report": "View report",
  "this_week": "This week",
  "low_stock_limit_label": "Low Stock Limit",
  "low_stock_label": "Low Stock",
  "pending": "Pending",
  "products": "products",
  "transactions": "transactions",
  "reports": "Reports",
  "high_margin_items": "High Margin Items",
  "stock_needed": "Stock Needed",
  "restock": "Restock",
  "no_items_yet": "No items yet. Add products from Stock.",
  "loading_shop_data": "Loading shop data...",
  "today": "Today",
  "this_month": "This Month",
  "six_months": "6 Months",
  "this_year": "This Year",
  "pdf_report": "PDF",
  "premium_pdf_report": "Premium PDF",
  "premium_pdf_requires_subscription": "Premium subscription required to download detailed PDF.",
  "premium_pdf_downloaded": "Premium PDF generated successfully.",
  "premium_pdf_fallback": "Premium PDF failed, falling back to basic PDF.",
  "left_limit": "left, limit",
  "highest_udhar": "Highest Udhar",
  "customer": "Customer",
  "add_customer": "Add Customer",
  "pending_amount": "Pending Amount",
  "customers": "Customers",
  "no_udhari_customers": "No udhari customers yet",
  "balance": "Balance",
  "payment": "Payment",
  "history": "History",
  "no_history": "No history yet",
  "recent": "Recent",
  "name_is_enough": "Name is enough. Mobile number is optional.",
  "customer_name": "Customer Name",
  "mobile_number": "Mobile Number",
  "save_customer": "Save Customer",
  "amount": "Amount",
  "note": "Note",
  "save_payment": "Save Payment",
  "receive_payment": "Receive Payment",
  "sale_bill": "Sale Bill",
  "quick_sale": "Quick Sale",
  "quick_sale_desc": "Search for items, select quantity or price variant, add to cart, and finalize the sale",
  "add_items_desc": "Add items and record transactions",
  "add_items": "Add Items",
  "sale_items": "Sale Items",
  "no_items_added": "No items added yet",
  "selling": "Selling",
  "cost": "Cost",
  "profit_amount": "Profit",
  "total_revenue": "Total Revenue",
  "total_cost": "Total Cost",
  "total_profit": "Total Profit",
  "payment_method": "Payment Method",
  "udhari_customer": "Udhari Customer",
  "new_customer": "New customer",
  "mobile": "Mobile",
  "optional": "Optional",
  "udhari_bill_notice": "This bill will appear in the customer's Udhari history.",
  "complete_sale": "Complete Sale",
  "processing": "Processing...",
  "cash": "Cash",
  "card": "Card",
  "partial": "Partial",
  "udhar": "Udhar",
  "confirm_sale_title": "Complete Sale?",
  "buy": "Buy",
  "sell": "Sell",
  "total_value_label": "Total Value",
  "price_variants": "Price Variants:",
  "low_stock_alert": "Low Stock",
  "price_tier": "Price Tier",
  "default_label": "Default",
  "total_price": "Total Price",
  "add_to_sale": "Add to Sale",
  "enter_quantity": "Enter quantity",
  "search_items": "Search items...",
  "daily_sales": "Daily Sales",
  "no_sales_day": "No sales on this day",
  "no_sales_day_desc": "Sales recorded on this day will appear here.",
  "day_summary": "Day Summary",
  "revenue": "Revenue",
  "items_sold": "Items Sold",
  "stock_left": "Stock Left",
  "per_unit": "per unit",
  "transaction": "Transaction",
  "credit_sale": "Credit Sale",
  "tap_to_expand": "Tap to see details",
  "previous_day": "Previous Day",
  "next_day": "Next Day",
  "shop": "Shop",
  "loading": "Loading...",
  "loading_dukan": "Loading Dukan...",
  "no_data": "No data available",
  "expand_menu": "Expand menu",
  "collapse_menu": "Collapse menu",
  "unread": "Unread",
  "total_label": "Total",
  "unknown": "Unknown",
  "color": "Color",
  "short_form": "Short form",
  "update": "Update",
  "actions": "Actions",
  "select_all": "Select All",
  "deselect_all": "Deselect All",
  "delete_confirm_title": "Delete?",
  "cannot_undo": "This action cannot be undone.",
  "login_title": "Dukan",
  "login_subtitle": "Sign in to manage your shop",
  "email": "Email",
  "password": "Password",
  "enter_email": "Enter your email",
  "enter_password": "Enter your password",
  "logging_in": "Logging in...",
  "login": "Login",
  "login_success": "Login successful!",
  "login_fill_fields": "Please enter both email and password",
  "redirecting_dashboard": "Redirecting to dashboard...",
  "reports_help": "View daily sales breakdowns or monthly profit and loss analysis",
  "daily_report": "Daily Report",
  "monthly_pl": "Monthly P&L",
  "daily_report_title": "Daily Report",
  "monthly_report_title": "Monthly P&L Report",
  "monthly_report_desc": "Profit and loss analysis for your shop",
  "back_to_sales": "Back to Sales",
  "total_transactions": "Total Transactions",
  "sales_completed": "Sales completed",
  "cost_of_goods": "Cost of Goods",
  "loading_report": "Loading report...",
  "no_sales_month": "No sales data for this month",
  "daily_breakdown": "Daily Breakdown",
  "top_selling_items": "Top Selling Items",
  "sold": "sold",
  "alerts_title": "Alerts",
  "alerts_desc": "Stock and expiry notifications for your shop.",
  "no_alerts": "No alerts right now",
  "no_alerts_desc": "Low stock and expiry alerts will appear here.",
  "severity_info": "info",
  "severity_warning": "warning",
  "severity_critical": "critical",
  "settings_desc": "Manage your pharmacy preferences and catalog",
  "language_desc": "Choose your preferred language",
  "language_note_en": "The application will be displayed in your selected language.",
  "about_title": "About Dukan",
  "about_subtitle": "Shop inventory management app",
  "about_body1": "Dukan is a simple inventory system for small grocery shops and retail businesses.",
  "about_body2": "Your data is stored locally on your device and works offline.",
  "version": "Version",
  "categories_desc": "Manage your product categories",
  "category_name_label": "Category Name",
  "category_name_marathi": "Category Name (Marathi)",
  "update_category_desc": "Update category details",
  "create_category_desc": "Create a new product category",
  "no_categories": "No categories added yet",
  "category_name_required": "Please enter a category name",
  "category_updated": "Category updated successfully",
  "category_added": "Category added successfully",
  "category_deleted": "Category deleted successfully",
  "category_save_error": "Error saving category",
  "category_delete_error": "Error deleting category",
  "delete_category_title": "Delete Category?",
  "delete_category_desc": "The category will be deleted permanently.",
  "units_desc": "Manage measurement units for your products",
  "unit_name_label": "Unit Name",
  "unit_name_marathi": "Unit Name (Marathi)",
  "short_form_label": "Short Form (e.g., kg, L)",
  "update_unit_desc": "Update unit details",
  "create_unit_desc": "Create a new measurement unit",
  "no_units": "No units added yet",
  "fill_all_fields": "Please fill all fields",
  "unit_updated": "Unit updated successfully",
  "unit_added": "Unit added successfully",
  "unit_deleted": "Unit deleted successfully",
  "unit_save_error": "Error saving unit",
  "unit_delete_error": "Error deleting unit",
  "delete_unit_title": "Delete Unit?",
  "delete_unit_desc": "The unit will be deleted permanently.",
  "items_desc": "Manage inventory, prices, and stock levels",
  "add_new_item": "Add New Item",
  "item_validation_error": "Please fill all fields correctly. Selling price must be greater than buying price.",
  "item_updated": "Item updated successfully",
  "item_added": "Item added successfully",
  "item_save_error": "Error saving item. Please try again.",
  "item_deleted": "Item deleted successfully",
  "item_delete_error": "Error deleting item",
  "items_bulk_deleted": "Deleted {count} item(s)",
  "items_bulk_delete_error": "Error deleting items",
  "item_name_en": "Item Name",
  "item_name_mr": "Item Name (Marathi)",
  "item_name_tooltip": "Product name as shown in your shop (e.g., Basmati Rice, Salt)",
  "item_name_mr_tooltip": "Product name in Marathi for local customers",
  "category_tooltip": "Organize medicines and healthcare products by category",
  "unit_tooltip": "Measurement unit (kg, L, pcs, g, ml) for stock and sales",
  "quantity_tooltip": "Current stock quantity in your shop",
  "buy_price_tooltip": "Cost price from supplier (Rs.)",
  "sell_price_tooltip": "Retail price for customers (Rs.)",
  "low_stock_tooltip": "Alert when stock falls below this level. Leave empty to disable.",
  "leave_empty_alerts": "Leave empty to disable alerts",
  "basic_info": "Basic Info",
  "pricing": "Pricing",
  "price_tiers_tab": "Price Tiers",
  "not_enough_stock": "Not enough stock",
  "stock_issue": "Stock issue",
  "only_available": "Only {qty} {unit} available"
};

const english = {
  language: "en" as AppLanguage,
  locale: "en-IN",
  t: (key: string): string => translations[key] || key,
  formatDate: (date: Date, options?: Intl.DateTimeFormatOptions) =>
    date.toLocaleDateString("en-IN", options),
};

const LanguageContext = createContext(english);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  return <LanguageContext.Provider value={english}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
