-- MediShop development extension. Additive; no customer/catalog data is deleted.
-- Apply after the existing schema and earlier migrations.
-- New-table policies follow this development app's existing custom-auth model.
-- These permissive policies are not production tenant authorization.
BEGIN;

ALTER TABLE public.items
  ADD COLUMN IF NOT EXISTS catalog_code text,
  ADD COLUMN IF NOT EXISTS icon_key text NOT NULL DEFAULT 'pill',
  ADD COLUMN IF NOT EXISTS generic_name text,
  ADD COLUMN IF NOT EXISTS strength text,
  ADD COLUMN IF NOT EXISTS dosage_form text,
  ADD COLUMN IF NOT EXISTS pack_type text,
  ADD COLUMN IF NOT EXISTS shelf_location text,
  ADD COLUMN IF NOT EXISTS batch_number text,
  ADD COLUMN IF NOT EXISTS gst_rate numeric CHECK (gst_rate >= 0 AND gst_rate <= 100),
  ADD COLUMN IF NOT EXISTS requires_prescription boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS cold_storage boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS supplier_name text,
  ADD COLUMN IF NOT EXISTS supplier_phone text;

ALTER TABLE public.credit_customers
  ADD COLUMN IF NOT EXISTS repeat_medicine text,
  ADD COLUMN IF NOT EXISTS repeat_every_days integer CHECK (repeat_every_days BETWEEN 1 AND 3650),
  ADD COLUMN IF NOT EXISTS last_purchase_date date;

ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS receipt_phone text;
ALTER TABLE public.sale_items
  ADD COLUMN IF NOT EXISTS generic_name text,
  ADD COLUMN IF NOT EXISTS strength text,
  ADD COLUMN IF NOT EXISTS dosage_form text,
  ADD COLUMN IF NOT EXISTS gst_rate numeric CHECK (gst_rate >= 0 AND gst_rate <= 100);

ALTER TABLE public.app_settings ALTER COLUMN language SET DEFAULT 'en';

CREATE TABLE IF NOT EXISTS public.cash_reconciliations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id bigint NOT NULL REFERENCES public.shops(id) ON DELETE CASCADE,
  date date NOT NULL,
  counted_amount numeric(14,2) NOT NULL CHECK (counted_amount >= 0),
  expected_amount numeric(14,2) NOT NULL CHECK (expected_amount >= 0),
  difference numeric(14,2) GENERATED ALWAYS AS (counted_amount - expected_amount) STORED,
  user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(shop_id, date)
);

CREATE TABLE IF NOT EXISTS public.medicine_returns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id bigint NOT NULL REFERENCES public.shops(id) ON DELETE CASCADE,
  item_id bigint REFERENCES public.items(id) ON DELETE SET NULL,
  item_name text NOT NULL,
  batch_number text,
  supplier_name text,
  quantity numeric NOT NULL CHECK (quantity > 0),
  expected_credit numeric(14,2) NOT NULL CHECK (expected_credit >= 0),
  received_credit numeric(14,2) CHECK (received_credit >= 0),
  status text NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'credited')),
  user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  request_id uuid NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'sent' AND received_credit IS NULL) OR (status = 'credited' AND received_credit IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS medicine_returns_shop_created ON public.medicine_returns(shop_id, created_at DESC);
ALTER TABLE public.cash_reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medicine_returns ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='cash_reconciliations' AND policyname='Development custom-auth cash access') THEN
    CREATE POLICY "Development custom-auth cash access" ON public.cash_reconciliations FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='medicine_returns' AND policyname='Development custom-auth returns access') THEN
    CREATE POLICY "Development custom-auth returns access" ON public.medicine_returns FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;
GRANT SELECT, INSERT, UPDATE ON public.cash_reconciliations, public.medicine_returns TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.cash_reconciliations_id_seq, public.medicine_returns_id_seq TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.reconcile_pharmacy_cash(p_shop_id bigint, p_date date, p_counted_amount numeric, p_user_id bigint)
RETURNS SETOF public.cash_reconciliations LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE expected numeric; saved public.cash_reconciliations;
BEGIN
  IF p_counted_amount IS NULL OR p_counted_amount < 0 OR p_counted_amount::text IN ('NaN','Infinity','-Infinity') OR p_date IS NULL THEN
    RAISE EXCEPTION 'Enter a date and a valid non-negative counted amount';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM public.users WHERE id=p_user_id AND shop_id=p_shop_id AND role='owner') THEN RAISE EXCEPTION 'An owner in this pharmacy is required'; END IF;
  -- Cash sales only; excludes opening float, expenses, withdrawals and credit collections.
  SELECT coalesce(sum(CASE WHEN payment_method='cash' THEN subtotal
    WHEN payment_method='partial' AND paid_via='cash' THEN paid_amount ELSE 0 END),0)
    INTO expected FROM public.sales WHERE shop_id=p_shop_id AND date=p_date;
  INSERT INTO public.cash_reconciliations(shop_id,date,counted_amount,expected_amount,user_id)
    VALUES(p_shop_id,p_date,round(p_counted_amount,2),round(expected,2),p_user_id)
    ON CONFLICT(shop_id,date) DO UPDATE SET counted_amount=excluded.counted_amount,
      expected_amount=excluded.expected_amount,user_id=excluded.user_id,updated_at=now()
    RETURNING * INTO saved;
  RETURN NEXT saved;
END $$;

CREATE OR REPLACE FUNCTION public.send_pharmacy_return(p_shop_id bigint,p_item_id bigint,p_quantity numeric,p_user_id bigint,p_request_id uuid)
RETURNS SETOF public.medicine_returns LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE product public.items; saved public.medicine_returns; batch record; remaining numeric; take_qty numeric; available numeric;
BEGIN
  IF p_quantity IS NULL OR p_quantity <= 0 OR p_quantity::text IN ('NaN','Infinity','-Infinity') OR p_request_id IS NULL THEN RAISE EXCEPTION 'A positive return quantity and request ID are required'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.users WHERE id=p_user_id AND shop_id=p_shop_id AND role='owner') THEN RAISE EXCEPTION 'An owner in this pharmacy is required'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_request_id::text,0));
  SELECT * INTO saved FROM public.medicine_returns WHERE request_id=p_request_id;
  IF FOUND THEN
    IF saved.shop_id<>p_shop_id OR saved.item_id<>p_item_id OR saved.quantity<>p_quantity THEN RAISE EXCEPTION 'Return request does not match the saved return'; END IF;
    RETURN NEXT saved; RETURN;
  END IF;
  SELECT * INTO product FROM public.items WHERE id=p_item_id AND shop_id=p_shop_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Medicine was not found in this pharmacy'; END IF;
  IF product.quantity<p_quantity THEN RAISE EXCEPTION 'Return quantity exceeds available stock'; END IF;
  IF nullif(trim(product.supplier_name),'') IS NULL THEN RAISE EXCEPTION 'Save a supplier before returning stock'; END IF;
  IF EXISTS(SELECT 1 FROM public.batches WHERE item_id=p_item_id AND shop_id=p_shop_id) THEN
    PERFORM 1 FROM public.batches WHERE item_id=p_item_id AND shop_id=p_shop_id ORDER BY id FOR UPDATE;
    SELECT coalesce(sum(quantity_available),0) INTO available FROM public.batches
      WHERE item_id=p_item_id AND shop_id=p_shop_id AND (nullif(product.batch_number,'') IS NULL OR batch_number=product.batch_number);
    IF available<p_quantity THEN RAISE EXCEPTION 'Batch stock is lower than the requested return; review the batch quantities'; END IF;
    remaining := p_quantity;
    FOR batch IN SELECT * FROM public.batches WHERE item_id=p_item_id AND shop_id=p_shop_id AND quantity_available>0
      AND (nullif(product.batch_number,'') IS NULL OR batch_number=product.batch_number) ORDER BY expiry_date NULLS LAST,id LOOP
      take_qty := least(remaining,batch.quantity_available);
      UPDATE public.batches SET quantity_available=quantity_available-take_qty,updated_at=now() WHERE id=batch.id;
      remaining := remaining-take_qty;
      EXIT WHEN remaining=0;
    END LOOP;
  END IF;
  UPDATE public.items SET quantity=quantity-p_quantity,updated_at=now() WHERE id=p_item_id AND shop_id=p_shop_id;
  INSERT INTO public.medicine_returns(shop_id,item_id,item_name,batch_number,supplier_name,quantity,expected_credit,user_id,request_id)
    VALUES(p_shop_id,p_item_id,coalesce(product.name,'Medicine'),product.batch_number,product.supplier_name,p_quantity,round(p_quantity*product.buy_price,2),p_user_id,p_request_id)
    RETURNING * INTO saved;
  INSERT INTO public.stock_history(shop_id,item_id,item_name,type,quantity_changed,quantity_before,quantity_after,reason,cost_per_unit,reference)
    VALUES(p_shop_id,p_item_id,saved.item_name,'adjustment',-p_quantity,product.quantity,product.quantity-p_quantity,'Sent to supplier; return credit pending',product.buy_price,'medicine-return:'||saved.id);
  RETURN NEXT saved;
END $$;

CREATE OR REPLACE FUNCTION public.credit_pharmacy_return(p_shop_id bigint,p_return_id bigint,p_received_credit numeric,p_user_id bigint)
RETURNS SETOF public.medicine_returns LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE saved public.medicine_returns;
BEGIN
  IF NOT EXISTS(SELECT 1 FROM public.users WHERE id=p_user_id AND shop_id=p_shop_id AND role='owner') THEN RAISE EXCEPTION 'An owner in this pharmacy is required'; END IF;
  IF p_received_credit IS NULL OR p_received_credit<0 OR p_received_credit::text IN ('NaN','Infinity','-Infinity') THEN RAISE EXCEPTION 'Enter a valid received credit amount'; END IF;
  SELECT * INTO saved FROM public.medicine_returns WHERE id=p_return_id AND shop_id=p_shop_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Return was not found'; END IF;
  IF saved.status='credited' THEN RAISE EXCEPTION 'Supplier credit is already recorded'; END IF;
  UPDATE public.medicine_returns SET status='credited',received_credit=round(p_received_credit,2),user_id=p_user_id,updated_at=now()
    WHERE id=saved.id RETURNING * INTO saved;
  RETURN NEXT saved;
END $$;

-- Safe activity summaries only. Never copy passwords, tokens, full customer rows or sale notes.
CREATE OR REPLACE FUNCTION public.log_pharmacy_activity() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE row_data jsonb; previous jsonb; summary jsonb; actor bigint;
BEGIN
  IF TG_OP='DELETE' THEN row_data:=to_jsonb(OLD); ELSE row_data:=to_jsonb(NEW); END IF;
  IF TG_OP='UPDATE' THEN previous:=to_jsonb(OLD); END IF;
  IF row_data->>'shop_id' IS NULL THEN RETURN NULL; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.shops WHERE id=(row_data->>'shop_id')::bigint) THEN RETURN NULL; END IF;
  summary:=jsonb_strip_nulls(jsonb_build_object('name',coalesce(row_data->>'name',row_data->>'item_name',row_data->>'username'),
    'quantity',row_data->'quantity','subtotal',row_data->'subtotal','status',row_data->'status','counted_amount',row_data->'counted_amount'));
  IF TG_TABLE_NAME IN ('cash_reconciliations','medicine_returns') THEN actor:=(row_data->>'user_id')::bigint; END IF;
  INSERT INTO public.audit_logs(shop_id,user_id,action,table_name,record_id,old_data,new_data)
    VALUES((row_data->>'shop_id')::bigint,actor,CASE TG_OP WHEN 'INSERT' THEN 'create' WHEN 'UPDATE' THEN 'update' ELSE 'delete' END,
      TG_TABLE_NAME,row_data->>'id',NULL,summary);
  RETURN NULL;
END $$;
DO $$ DECLARE table_name text; BEGIN
  FOREACH table_name IN ARRAY ARRAY['items','sales','credit_customers','users','cash_reconciliations','medicine_returns'] LOOP
    IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid=format('public.%I',table_name)::regclass AND tgname='medishop_activity') THEN
      EXECUTE format('CREATE TRIGGER medishop_activity AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.log_pharmacy_activity()',table_name);
    END IF;
  END LOOP;
END $$;
GRANT EXECUTE ON FUNCTION public.reconcile_pharmacy_cash(bigint,date,numeric,bigint), public.send_pharmacy_return(bigint,bigint,numeric,bigint,uuid), public.credit_pharmacy_return(bigint,bigint,numeric,bigint) TO anon, authenticated;
NOTIFY pgrst, 'reload schema';
COMMIT;
